@startuml

package HTTP_layer <<Folder>> {
    abstract class ControllerBase

    class SecurityController extends ControllerBase {
        #ManagerInterface securityManager
        #ViewJspInterface loginViewJsp

        +void loginAction()
        +void logoutAction()
        +void loginCheckAction()
    }

    class UserController extends ControllerBase {
        #ManagerInterface userManager
        #ViewJspInterface userViewJsp
        #ViewJspInterface usersListViewJsp

        +void getUserAction()
        +void getUserListAction()
        +void createUserAction()
        +void updateUserAction()
        +void deleteUserAction()
    }

    class LogController extends ControllerBase {
        #ManagerInterface logReaderManager
        #ViewJspInterface logRecordViewJsp
        #ViewJspInterface logRecordsViewJsp

        +void getLogListAction(Map<String, String> criteria, Map<String, String> orderBy, int limit, int offset)
        +void getLogRecord(int logRecordId)
    }
}

package View_layer <<Folder>> {
    interface ViewJspInterface

    class UserViewJsp implements ViewJspInterface {
    }

    class UsersListViewJsp implements ViewJspInterface  {
    }

    class LogRecordViewJsp implements ViewJspInterface  {
    }

    class LogRecordsListViewJsp implements ViewJspInterface  {
    }

    class LoginViewJsp implements ViewJspInterface {
    }
}

package Database_layer <<Database>> {
    interface EntityInterface

    class User implements EntityInterface {
        ROLE_USER: String = "ROLE_USER"
        ROLE_ADMIN: String = "ROLE_ADMIN"
        -int id
        -String username
        -String passwordHash
        -String email
        -Date lastLogin
        -ArrayList<String> roles
    }

    class LogRecord implements EntityInterface {
        -String remoteIp
        -int errorLevel
        -Date created
        -String resourceName
        -String userLogin
    }
}

package Logic_layer <<Folder>> {
    interface ManagerInterface

    class UserManager implements ManagerInterface
    class LogManager implements ManagerInterface
}

SecurityController "1" *-- "1" LoginViewJsp : contains
UserController "1" *-- "1" UserViewJsp : contains
UserController "1" *-- "1" UsersListViewJsp : contains
LogController "1" *-- "1" LogRecordViewJsp : contains
LogController "1" *-- "1" LogRecordsListViewJsp: contains



@enduml