<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%--
  Created by IntelliJ IDEA.
  User: Dmitriy
  Date: 09.03.2016
  Time: 15:07
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Calculator</title>
</head>
<body>
<center>
    <form>
        <table>
            <div id="fullexpression">
                <tr align="right" valign="top">
                    0
                </tr>
            </div>
            <div id="currentnumber">
                <tr align="right" valign="top">
                    0
                </tr>
            </div>
            <tr>
                <td>
                    <button>
                        x!
                    </button>
                </td>
                <td>
                    <button>
                        x!
                    </button>
                </td>
                <td>
                    <button>
                        x!
                    </button>
                </td>
                <td>
                    <button>
                        x!
                    </button>
                </td>
                <td>
                    <button>
                        x!
                    </button>
                </td>
            </tr>
            <tr>
                <td>
                    <button>
                        x!
                    </button>
                </td>
                <td>
                    <button>
                        x!
                    </button>
                </td>
                <td>
                    <button>
                        x!
                    </button>
                </td>
                <td>
                    <button>
                        x!
                    </button>
                </td>
                <td>
                    <button>
                        x!
                    </button>
                </td>
            </tr>
            <tr>
                <td>
                    <button>
                        x!
                    </button>
                </td>
                <td>
                    <button>
                        x!
                    </button>
                </td>
                <td>
                    <button>
                        x!
                    </button>
                </td>
                <td>
                    <button>
                        x!
                    </button>
                </td>
                <td>
                    <button>
                        x!
                    </button>
                </td>
            </tr>
            <tr>
                <td>
                    <button>
                        x!
                    </button>
                </td>
                <td>
                    <button>
                        x!
                    </button>
                </td>
                <td>
                    <button>
                        x!
                    </button>
                </td>
                <td>
                    <button>
                        x!
                    </button>
                </td>
                <td>
                    <button>
                        x!
                    </button>
                </td>
            </tr>
            <tr>
                <td>
                    <button>
                        x!
                    </button>
                </td>
                <td>
                    <button>
                        x!
                    </button>
                </td>
                <td>
                    <button>
                        x!
                    </button>
                </td>
                <td>
                    <button>
                        x!
                    </button>
                </td>
                <td>
                    <button>
                        x!
                    </button>
                </td>
            </tr>
        </table>
    </form>
</center>
</body>
</html>
